### ISSUE TITLE
Invalid require condition

### ISSUE THREAD

**Issue by clowestab** [Consensys/linea-ens#227]
# #https://github.com/Consensys/linea-ens/blob/1da40ef3b757b708bf2054954b36cf94cbc66266/packages/linea-state-verifier/contracts/LineaSparseProofVerifier.sol#L43

The above require condition is invalid. In the context of the `L1Resolver` the `acceptedL2BlockRangeLength` is set to 86400 (1 day) - https://github.com/Consensys/linea-ens/blob/d139c5ce34630ee383152ef977539a099300a996/packages/linea-ens-resolver/contracts/L1Resolver.sol#L42

The check is against a block number and noting the `currentL2BlockNumber` (7581832) in the Linea rollup contract (https://etherscan.io/address/0xd19d4B5d358258f05D7B411E21A1460D11B0876F#readProxyContract) this check will always evaluate to `false`.

**Comment by Julink-eth** [comment]
Closing since this has been discussed and explained that it is required to be generic and work for new networks. (Example testnet that will come after sepolia)
